"""Deterministic comparison domain."""

from app.comparison.constants import (
    GOVERNMENT_WARNING_HEADING,
    GOVERNMENT_WARNING_SOURCE_URL,
    GOVERNMENT_WARNING_TEXT,
)
from app.comparison.models import (
    ApplicationErrorCategory,
    CheckName,
    CheckResult,
    CheckStatus,
    ExpectedNetContents,
    ExpectedReview,
    ExtractionObservations,
    FieldObservation,
    NetContentsUnit,
    OverallOutcome,
    Readability,
    ReviewResult,
    SafeApplicationError,
    TextCandidate,
    TextWeight,
    Visibility,
    WarningObservation,
)
from app.comparison.service import (
    compare_alcohol_content,
    compare_brand,
    compare_class_type,
    compare_government_warning,
    compare_net_contents,
    compare_review,
    derive_overall_outcome,
    unable_to_process_result,
)

__all__ = [
    "GOVERNMENT_WARNING_HEADING",
    "GOVERNMENT_WARNING_SOURCE_URL",
    "GOVERNMENT_WARNING_TEXT",
    "ApplicationErrorCategory",
    "CheckName",
    "CheckResult",
    "CheckStatus",
    "ExpectedNetContents",
    "ExpectedReview",
    "ExtractionObservations",
    "FieldObservation",
    "NetContentsUnit",
    "OverallOutcome",
    "Readability",
    "ReviewResult",
    "SafeApplicationError",
    "TextCandidate",
    "TextWeight",
    "Visibility",
    "WarningObservation",
    "compare_alcohol_content",
    "compare_brand",
    "compare_class_type",
    "compare_government_warning",
    "compare_net_contents",
    "compare_review",
    "derive_overall_outcome",
    "unable_to_process_result",
]
